; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=slp-vectorizer -S %s | FileCheck %s

define i32 @test() {
entry:
  %mul = mul i32 1, 0
  %shl = shl i32 %mul, 0
  %xor1 = xor i32 %shl, %mul
  ret i32 %xor1
}
